name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm i
          
      - name: lint
        run: npm run lint

      - name: tsc:check
        run: npm run tsc:check
        
      - name: build 
        run: npm run build
